name: Release

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      DATE: ${{ steps.get_date.outputs.DATE }}
    steps:
      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  windows:
    strategy:
      matrix:
        os-version: ['x64', 'arm64']

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build
        run: |
          pnpm install
          pnpm fetchcore
          pnpm run build:win-${{ matrix.os-version }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: zip-unpacked-x64
        if: matrix.os-version == 'x64'
        run: |
          cd .\dist\win-unpacked
          7z a -r Final2x-windows-${{ matrix.os-version }}-unpacked.7z *

      - name: zip-unpacked-arm64
        if: matrix.os-version == 'arm64'
        run: |
          cd .\dist\win-arm64-unpacked
          7z a -r Final2x-windows-${{ matrix.os-version }}-unpacked.7z *

      - name: upload-unpacked-x64
        if: matrix.os-version == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: Final2x-windows-${{ matrix.os-version }}-unpacked
          path: dist/win-unpacked/*.7z

      - name: upload-unpacked-arm64
        if: matrix.os-version == 'arm64'
        uses: actions/upload-artifact@v4
        with:
          name: Final2x-windows-${{ matrix.os-version }}-unpacked
          path: dist/win-arm64-unpacked/*.7z

  macos:
    strategy:
      matrix:
        os-version: ['arm64']

    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build
        run: |
          pnpm install
          pnpm fetchcore
          pnpm run build:mac-${{ matrix.os-version }}
        env:
          ARCH: ${{ matrix.os-version }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: rename
        run: |
          cd ./dist
          mv *.dmg Final2x-macos-${{ matrix.os-version }}-dmg.dmg

      - name: zip-unpacked-arm64
        if: matrix.os-version == 'arm64'
        run: |
          cd ./dist/mac-arm64
          7z a -r Final2x-macos-${{ matrix.os-version }}-unpacked.7z *

      - name: upload-dmg
        uses: actions/upload-artifact@v4
        with:
          name: Final2x-macos-${{ matrix.os-version }}-dmg
          path: dist/*.dmg

      - name: upload-unpacked-arm64
        if: matrix.os-version == 'arm64'
        uses: actions/upload-artifact@v4
        with:
          name: Final2x-macos-${{ matrix.os-version }}-unpacked
          path: dist/mac-arm64/*.7z

  linux-pip:
    strategy:
      matrix:
        os-version: ['x64']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build
        run: |
          pnpm install
          pnpm run build:linux-${{ matrix.os-version }}
        env:
          SKIP_DOWNLOAD_CORE: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: zip-unpacked
        run: |
          cd ./dist/linux-unpacked
          7z a -r Final2x-linux-pip-${{ matrix.os-version }}-unpacked.7z *

      - name: rename
        run: |
          cd ./dist
          mv *.snap Final2x-linux-pip-${{ matrix.os-version }}-snap.snap
          mv *.AppImage Final2x-linux-pip-${{ matrix.os-version }}-AppImage.AppImage
          mv *.deb Final2x-linux-pip-${{ matrix.os-version }}-deb.deb

      - name: upload-snap
        uses: actions/upload-artifact@v4
        with:
          name: Final2x-linux-pip-${{ matrix.os-version }}-snap
          path: dist/*.snap

      - name: upload-AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Final2x-linux-pip-${{ matrix.os-version }}-AppImage
          path: dist/*.AppImage

      - name: upload-deb
        uses: actions/upload-artifact@v4
        with:
          name: Final2x-linux-pip-${{ matrix.os-version }}-deb
          path: dist/*.deb

      - name: upload-unpacked
        uses: actions/upload-artifact@v4
        with:
          name: Final2x-linux-pip-${{ matrix.os-version }}-unpacked
          path: dist/linux-unpacked/*.7z

  Release:
    needs: [setup, windows, macos, linux-pip]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: asset

      - name: Flatten asset directory
        run: |
          tree asset
          mkdir dist
          find asset -type f -print0 | xargs -0 -I{} cp "{}" dist/
          cd dist && ls -l

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ needs.setup.outputs.DATE }}
          tag_name: ${{ needs.setup.outputs.DATE }}
          body: Auto Release.
          draft: false
          prerelease: false
          files: dist/*
